In [104]:
#Import libraries
import warnings 
warnings.filterwarnings('ignore')
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np
import pickle

In [105]:
# Load your dataset
df = pd.read_csv('moviedataset.csv', encoding='ISO-8859-1', comment='#', quotechar='"', skipinitialspace=True)
df.shape

(15506, 10)

In [106]:
#Data cleaning
df = df.dropna()
df.shape

(5656, 10)

In [107]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
2,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
5,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
6,@Andheri,(2014),116 min,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair,Augustine,Fathima Babu,Byon
7,1:1.6 An Ode to Lost Love,(2004),96 min,Drama,6.2,17,Madhu Ambat,Rati Agnihotri,Gulshan Grover,Atul Kulkarni

In [108]:
df = df.drop(['Name', 'Actor 1', 'Actor 2', 'Actor 3'], axis=1)
df.head()

,Year,Duration,Genre,Rating,Votes,Director
2,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail
3,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar
5,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel
6,(2014),116 min,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair
7,(2004),96 min,Drama,6.2,17,Madhu Ambat

In [109]:
df['Year'] = df['Year'].astype(str).str.extract('(\d+)').astype(int)
df

,Year,Duration,Genre,Rating,Votes,Director
2,1997,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail
3,2005,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar
5,2012,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel
6,2014,116 min,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair
7,2004,96 min,Drama,6.2,17,Madhu Ambat
...,...,...,...,...,...,...
15490,2015,115 min,Drama,6.1,408,Mozez Singh
15491,2001,153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal
15500,1989,125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman
15502,1999,129 min,"Action, Drama",4.5,655,Kuku Kohli
15505,1998,130 min,"Action, Drama",6.2,20,K.C. Bokadia

In [110]:
df['Duration'] = df['Duration'].astype(str)
df['Duration'] = df['Duration'].str.replace(' min', '').astype(int)
df

,Year,Duration,Genre,Rating,Votes,Director
2,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail
3,2005,142,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar
5,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel
6,2014,116,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair
7,2004,96,Drama,6.2,17,Madhu Ambat
...,...,...,...,...,...,...
15490,2015,115,Drama,6.1,408,Mozez Singh
15491,2001,153,"Biography, Drama, History",6.2,"1,496",Shyam Benegal
15500,1989,125,"Action, Crime, Drama",5.8,44,S.P. Muthuraman
15502,1999,129,"Action, Drama",4.5,655,Kuku Kohli
15505,1998,130,"Action, Drama",6.2,20,K.C. Bokadia

In [111]:
df_genres = df['Genre'].str.get_dummies(sep=', ')
df = pd.concat([df, df_genres], axis=1).drop('Genre', axis=1)
df

,Year,Duration,Rating,Votes,Director,Action,Adventure,Animation,Biography,Comedy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
2,1997,147,4.7,827,Rahul Rawail,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,2005,142,7.4,"1,086",Shoojit Sircar,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5,2012,82,5.6,326,Allyson Patel,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
6,2014,116,4.0,11,Biju Bhaskar Nair,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,2004,96,6.2,17,Madhu Ambat,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15490,2015,115,6.1,408,Mozez Singh,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15491,2001,153,6.2,"1,496",Shyam Benegal,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,1989,125,5.8,44,S.P. Muthuraman,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15502,1999,129,4.5,655,Kuku Kohli,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15505,1998,130,6.2,20,K.C. Bokadia,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [112]:
df['Votes'] = df['Votes'].str.replace(',', '').astype(int)
df

,Year,Duration,Rating,Votes,Director,Action,Adventure,Animation,Biography,Comedy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
2,1997,147,4.7,827,Rahul Rawail,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,2005,142,7.4,1086,Shoojit Sircar,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5,2012,82,5.6,326,Allyson Patel,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
6,2014,116,4.0,11,Biju Bhaskar Nair,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,2004,96,6.2,17,Madhu Ambat,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15490,2015,115,6.1,408,Mozez Singh,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15491,2001,153,6.2,1496,Shyam Benegal,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,1989,125,5.8,44,S.P. Muthuraman,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15502,1999,129,4.5,655,Kuku Kohli,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15505,1998,130,6.2,20,K.C. Bokadia,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [113]:
label_encoder = LabelEncoder()
df['Director'] = label_encoder.fit_transform(df['Director'])
df

,Year,Duration,Rating,Votes,Director,Action,Adventure,Animation,Biography,Comedy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
2,1997,147,4.7,827,1527,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,2005,142,7.4,1086,2041,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5,2012,82,5.6,326,135,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
6,2014,116,4.0,11,401,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,2004,96,6.2,17,1081,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15490,2015,115,6.1,408,1221,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15491,2001,153,6.2,1496,2056,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,1989,125,5.8,44,1790,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15502,1999,129,4.5,655,1023,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15505,1998,130,6.2,20,893,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [114]:
X = df.drop(['Rating'], axis=1)
y = df['Rating']

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [116]:
models = {
    'Random Forest': RandomForestRegressor(),
    'Linear Regression': LinearRegression(),
    'Gradient Boosting': GradientBoostingRegressor()
}
for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    print(f'{name} - MSE: {mse:.4f}, RMSE: {rmse:.4f}')

Random Forest - MSE: 1.1583, RMSE: 1.0762
Linear Regression - MSE: 1.5797, RMSE: 1.2568
Gradient Boosting - MSE: 1.1095, RMSE: 1.0533

In [117]:
best_model = GradientBoostingRegressor()
best_model.fit(X_train, y_train)

GradientBoostingRegressor()

In [118]:
predictions = best_model.predict(X_test)
predictions

array([5.09558833, 6.58831483, 6.30427243, ..., 6.33836034, 4.77026549,
       6.19159091])

In [118]:
new_data = [[3, 1, 22.0, 1, 0, 7.2500, 2]]  # Example input, adjust as needed
prediction = model.predict(new_data)
print(f"Rating is: {prediction[0]}")

array([5.09558833, 6.58831483, 6.30427243, ..., 6.33836034, 4.77026549,
       6.19159091])

In [119]:
with open('gradient_boosting_model.pkl', 'wb') as model_file:
    pickle.dump(best_model, model_file)